### ISSUE TITLE
你好！非常感谢你将代码开源，给我们提供了非常大的帮助。请问可以提供一下数据集吗？非常感谢！ 

### ISSUE THREAD

**Issue by SE-GZ** [JennahF/AutoS2AE#1]

**Comment by SE-GZ** [comment]
或者可否提供一下数据的格式，比如输入的数据维度，第一个维度表示用户，第二个维度表示所有物品之类的，对于代码的输入数据格式不是很清楚，非常感谢你！

**Comment by JennahF** [comment]
抱歉回复较慢。感谢你喜欢我们的工作。数据集已经更新到main分支中了。

**Comment by SE-GZ** [comment]
你好，收到了收到了，非常感谢~
